### ISSUE TITLE
Support for amazon.it

### ISSUE THREAD

**Issue by antoniofurleo1003** [LucaTNT/telegram-bot-amazon#13]
Hello, i did all the things you write and my bot workink! But the bot gave to people links of amazon.COM, i'm in italy and the link is invalid but if i change manually the website url in amazon.IT, it works without problems. I used the docker method

**Comment by LucaTNT** [comment]
Hi Antonio,
you just need to supply the `AMAZON_TLD` environment variable when you start the container:

    docker run -e AMAZON_TLD=it -e TELEGRAM_BOT_TOKEN=your-token -e AMAZON_TAG=your-tag --init lucatnt/telegram-bot-amazon

It should work no problem with the variable set that way.

**Comment by antoniofurleo1003** [comment]
Solved. Thank you!
