### ISSUE TITLE
Add support for channels

### ISSUE THREAD

**Issue by LucaTNT** [LucaTNT/telegram-bot-amazon#19]
As mentioned in #18, channels are not currently supported.

This needs to be investigated and, if possible, implemented.

**Comment by LucaTNT** [comment]
Note to self: this has been implemented by @nsniteshsahni [in this commit to his fork](https://github.com/nsniteshsahni/telegram-bot-amazon/commit/b1b814083c83089f44293adbd622ac87be8f19e8).

**Comment by theRAGEhero** [comment]
Hello Luca,
Would it be possible to merge it and update the new docker image?
Thank you

**Comment by LucaTNT** [comment]
Hi @theRAGEhero,
the implementation as-is is incomplete, as it would require a channel to be defined for the bot to work.
IMHO it should be optional.
I am low on free time and don't really need the feature, so PR are definitely welcome, but I don't know when I'll have the time to implement it myself.

**Comment by LucaTNT** [comment]
Channels support has been implemented, see the README.

Docker image has been updated as well, it is now at version `0.14`.

**Comment by theRAGEhero** [comment]
Thank you a lot!

On July 2, 2022 7:41:45 PM GMT+02:00, Luca Zorzi ***@***.***> wrote:
>Channels support has been implemented, see the README.
>
>Docker image has been updated as well, it is now at version `0.14`.
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/LucaTNT/telegram-bot-amazon/issues/19#issuecomment-1172934201
>You are receiving this because you were mentioned.
>
>Message ID: ***@***.***>

-- 
Inviato dal mio dispositivo Android con K-9 Mail. Perdonate la brevità.
