### ISSUE TITLE
GROUP_REPLACEMENT_MESSAGE

### ISSUE THREAD

**Issue by gamesswitch** [LucaTNT/telegram-bot-amazon#41]
Hi, 

Probably a silly question, but how do I make changes to the index.js? I need to change the GROUP_REPLACEMENT_MESSAGE, however can't seem to find a way to do it. 

I managed to get the bot to work by running the docker command, but it works with the default values 

Thanks in advance.

**Comment by LucaTNT** [comment]
Hi,
just add `-e GROUP_REPLACEMENT_MESSAGE="Whatever you want to set here"` to your Docker command.

For example:

    docker run -e TELEGRAM_BOT_TOKEN=your-token -e AMAZON_TAG=your-tag -e GROUP_REPLACEMENT_MESSAGE="Whatever you want to set here" --init lucatnt/telegram-bot-amazon
