### ISSUE TITLE
problem with the Amazon app generating .eu links that the bot does not recognize

### ISSUE THREAD

**Issue by LostTree0071** [LucaTNT/telegram-bot-amazon#78]
amazon app generates .eu links that bot doesn't recognize how can we fix?

**Comment by LucaTNT** [comment]
The `CHECK_FOR_REDIRECTS` setting is supposed to detect shortened links. Isn't it working with your .eu links?

**Comment by LostTree0071** [comment]
io utilizzo docker con il comando scritto nel file readme mettendo le variabili Amazon tld, telegram tocken , referral tag e il group replacement message, io non so se check for redirects sia su true, come dovrei fare per controllare il codice su docker?

**Comment by LucaTNT** [comment]
Aggiungi `-e CHECK_FOR_REDIRECTS=true` al comando.

**Comment by LostTree0071** [comment]
Thank you very much for your help but above all for making this wonderful bot available to everyone!
