### ISSUE TITLE
Da dove cominciare

### ISSUE THREAD

**Issue by DotHack88** [LucaTNT/telegram-bot-amazon#84]
Ciao a tutti ho scaricato il file zip ma non so proprio da dove iniziare

![Schermata 2022-12-22 alle 11 57 46](https://user-images.githubusercontent.com/40268801/209119743-82f8bbd0-233c-48ee-b18e-9ea18c575618.png)

**Comment by LucaTNT** [comment]
Mi spiace ma questo non è un forum di supporto per l'applicazione. Nel readme sono indicate le modalità di uso tramite Docker o direttamente con node, purtroppo non ho modo di fornire ulteriore assistenza a riguardo.
